### ISSUE TITLE
Ports forward

### ISSUE THREAD

**Issue by Ge0Lin** [n7tae/IcomGateway#1]
What TCP and UDP ports do I need to forward through the router in front of my Gateway?
TNX!

**Comment by n7tae** [comment]
If you want to allow outside users to callsign route into your repeater (most admins of public repeaters don't allow this) open UDP ports 40000 for IPv4 rounding and 9011 for IPv6 routing.

If you want to allow incoming nodes to link to your repeater, open UDP ports 20001 for REF linking. Inbound DCS and XRF linking is not supported. To allow DCS and XRF users access to to repeater, you'll need to link your module(s) to a multi-protocol reflector. Of course, if you do this, you REF users can link to the your module(s) through the connected reflector so you don't have to open the REF port.
